# library(conflicted)
library(targets)
library(tarchetypes)
# library(rmarkdown)
library(cli)
library(dplyr)
library(fst)
# library(future)
library(glue)
# library(gt)
library(magrittr)
# library(pingr)
library(pipload)
library(progress)
library(purrr)
library(qs)
# library(rstudioapi)
# library(shiny)
# library(shinycssloaders)
# library(shinyWidgets)
library(visNetwork)
library(wbpip)
library(fastverse)

fastverse_conflicts()
conflicted::conflicts_prefer(data.table::between())
conflicted::conflicts_prefer(collapse::funique())
conflicted::conflicts_prefer(data.table::first())
conflicted::conflict_scout()
